# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image:
  name: eclipse-temurin:8u422-b05-jdk

# using defaults for every job is preferred
# instead of using globals, if keyword supported
default:
  interruptible: true
  before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
  cache:
    untracked: false
    when: on_success
    paths:
      - '**/*.gradle*'
      - '**/gradle-wrapper.properties'

stages:
  - build
  - test
  - release_pre
  - release
  - deploy

variables:
  APP_NAME: 'test-app'
  BUILD_DIR: 'client/build/libs'
  ENVIRONMENT: 'Production'

build:
  stage: build
  script:
    - ./gradlew build --no-daemon

include:
  - template: Security/SAST.gitlab-ci.yml

test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test --no-daemon

release_pre:
  stage: release_pre
  dependencies:
    - build
    - test
  script:
    - chmod +x version.sh
    - VERSION_OLD=$(cat version)
    - VERSION=$(./version.sh $VERSION_OLD)
    - echo "VERSION_OLD=$VERSION_OLD" >> ${GITHUB_ENV:-build.env}
    - echo "VERSION=$VERSION" >> ${GITHUB_ENV:-build.env}
    - echo $VERSION > version
    - git config user.name "DevOps User"
    - git config user.email "devops@company.com"
    - git add version
    - git commit -m "[skip-ci] Automatic Bump Version from ${VERSION_OLD} to ${VERSION}."
    - git push
  artifacts:
    untracked: false
    when: on_success
    reports:
      dotenv: build.env

release_post:
  stage: release
  dependencies:
    - build
    - test
    - release_pre
  script:
    - ./gradlew jar --no-daemon
    - mv -v ${BUILD_DIR}/*.jar ${APP_NAME}_${VERSION}.jar
  release:
    # Description is REQUIRED
    description: "DESCRIPTION: Automatic Release ${VERSION}"
    name: "NAME: Automatic Release ${VERSION}"
    tag_name: ${VERSION}
  artifacts:
    when: on_success
    untracked: false
    name: ${APP_NAME}_${VERSION}
    access: all
    paths:
      - version
      - Readme.txt
      - ${APP_NAME}_${VERSION}.jar
    expire_in: "7 days"

deploy:
  stage: deploy
  dependencies:
    - build
    - test
    - release_post # pre and post
  environment:
    name: Production
    url: $CI_REPOSITORY_URL
    action: start
    deployment_tier: production
  
  script:
    - ./gradlew publish --no-daemon
