# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle
# https://github.com/actions/upload-artifact

name: Test CI Pipeline for Build and Release and Deploy

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'version'
      - 'version.sh'
    branches:
      - master
      - release

env:
  # VERSION FROM FILE
  APP_NAME: 'test-app'
  BUILD_DIR: 'client/build/libs'
  ENVIRONMENT: 'Production'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - run: ./gradlew build

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    needs:
      - build
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - run: ./gradlew test

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    needs:
      - build
      - test

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "DevOps User"
          git config user.email "devops@company.com"

      - run: |
          chmod +x version.sh
          ver=$(cat version)
          ver2=$(./version.sh $ver)
          echo "VERSION_OLD=$ver" >> $GITHUB_ENV
          echo "VERSION=$ver2" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - run: |
          ./gradlew jar
          mv -v ${{ vars.BUILD_DIR}}/*.jar ${{ vars.APP_NAME }}_${{ vars.VERSION }}.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Automatic Release ${{ vars.VERSION }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ vars.VERSION }}"
          draft: false
          prerelease: false
          files: |
            version
            Readme.txt
            ${{ vars.APP_NAME }}_${{ vars.VERSION }}.jar

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.APP_NAME }}_${{ vars.VERSION }}
          if-no-files-found: error
          retention-days: 7
          compression-level: 0
          overwrite: true
          include-hidden-files: false
          path: |
            version
            Readme.txt
            ${{ vars.APP_NAME }}_${{ vars.VERSION }}.jar

      - run: |
          echo ${{ vars.VERSION }} > version
          git add version
          git commit -m "Automatic Bump Version from ${{ vars.VERSION_OLD }} to ${{ vars.VERSION }}."
          git push

  deploy:
    runs-on: ubuntu-latest

    permissions:
     contents: read
     deployments: write

    needs:
      - build
      - test
      - release

    environment:
      name: ${{ vars.ENVIRONMENT }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - run: |
          ver=$(cat version)
          echo "VERSION=$ver" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: ${{ vars.APP_NAME }}_${{ vars.VERSION }}

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - run: ./gradlew publish
