# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle
# https://github.com/actions/upload-artifact

name: Test CD Pipeline for Deployment

on:
 release:
   types: [created]

env:
  # VERSION FROM FILE
  APP_NAME: 'test-app'
  BUILD_DIR: 'client/build/libs'
  REPO_DIR: 'repodir'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
     contents: read
     deployments: write

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Collect version
        run: |
          ver=$(cat version)
          echo "VERSION=$ver" >> $GITHUB_ENV

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ env.VERSION }}

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Deploy release to configured Maven repository
        run: ./gradlew publish
