# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle
# https://github.com/actions/upload-artifact

name: Test CICD Pipeline

on:
  push:
    branches:
      - master
      - release
#  release:
#    types: [created]
env:
  appname: 'test-app'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build
    
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Collect version
        run: VERSION = $(cat version)

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Create Release jars
        run: ./gradlew jar

      - name: "Create release in GitHub"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Automatic Release ${ VERSION }"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${ VERSION }"
          draft: false
          prerelease: false
          files: |
            LICENSE
            *.jar

      - name: Upload Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${ appname }-${ VERSION }
          path: |
            ./build/libs/client-${ VERSION }.jar
            ./build/libs/server-${ VERSION }.jar
          if-no-files-found: error
          retention-days: 7
          compression-level: 0
          overwrite: true
          include-hidden-files: false

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${ appname }-${ VERSION }

      - name: Deploy release to Maven and GitHub repositories
        run: ./gradlew publish
        env: 
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
